---
- name: Converge
  hosts: instances
  tasks:
    - name: Call Generate Token Role
      include_role:
        name: ansible-role-nginx-controller-generate-token
      vars:
        nginx_controller_fqdn: mock-server.molecule-test:1080
        nginx_controller_validate_certs: false
        nginx_controller_user_email: test@test.com
        nginx_controller_user_password: thisismypassword

    - name: Save Auth Token variable to a file on the mock server so we can consume it in the verify playbook
      copy:
        content: "{{ nginx_controller_auth_token }}"
        dest: "/tmp/verify-variable"
        mode: 0644
      changed_when: false
      delegate_to: mock-server
